#!/data/data/com.termux/files/usr/bin/bash

cd $HOME
###
pkg update && pkg -y upgrade 
pkg install -y git ruby
###
gem install bundler
###
git clone https://github.com/rapid7/metasploit-framework.git 
cd metasploit-framework
###
bundle install
###
ln -sf msfconsole $PREFIX/bin/msfconsole
