#!/data/data/com.termux/files/usr/bin/bash

apt update 
apt upgrade -y -o Dpkg::Options::="--force-confnew"
apt install -y binutils python3 python-pip autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git ruby -o Dpkg::Options::="--force-confnew"
apt install ruby clang make pkg-config libxml2 libxslt -y
python3 -m pip install requests

#
if [ -d "$PREFIX/opt/metasploit-framework" ]; then
  rm -rf $PREFIX/opt/metasploit-framework
fi

#
if [ ! -d "$PREFIX/opt" ]; then
  mkdir $PREFIX/opt
fi

#
git clone --depth=1 https://github.com/rapid7/metasploit-framework.git $PREFIX/opt/metasploit-framework
cd $PREFIX/opt/metasploit-framework

#
gem install bundler
gem install nokogiri
gem install nokogiri --platform ruby
bundle install

#
gem install actionpack
bundle update activesupport
bundle update --bundler
bundle install -j$(nproc --all)

#
ln -sf $PREFIX/opt/metasploit-framework/msfconsole $PREFIX/bin/
ln -sf $PREFIX/opt/metasploit-framework/msfvenom $PREFIX/bin/
ln -sf $PREFIX/opt/metasploit-framework/msfrpcd $PREFIX/bin/

#
termux-elf-cleaner $PREFIX/lib/ruby/gems/*/gems/pg-*/lib/pg_ext.so
